### ISSUE TITLE
Pin error when call transferCNB()

### ISSUE THREAD

**Issue by sandalwoods** [MixinNetwork/bot-api-swift-client#1]
In "Example" page, click "Run" button.

other func works fine, but for transferCNB(), pop up error: 

Transfer 1 CNB to someone...
Error: IncorrectPin
Ended

I believe i put right  pin code (6 digits number)  below:
api.payment.transfer(assetID: cnb, opponentID: opponent, amount: "1", memo: "Hello", pin: pin, traceID: traceID)

Could you please kindly advise what's wrong?

**Comment by wuyuehyang** [comment]
This project is still under construction. Try the latest demo to see if that happens again.
The issue will be closed for now since I can't reproduce it. Feel free to reopen it if similar problem still exists, or access our developers group of Mixin ID 7000104112 for support.
